name: Update Languages Table

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update Languages Table
        uses: desvelao/gh-languages-table@v1
        with:
          readme-path: README.md
